### PR TITLE
Major refactoring

### PR DESCRIPTION
**Pull request by TomasHofman**
- simple administration
- report showing all unknown members of github organization
- new UI

### CODE REVIEW

**Comment by wolfc** [comment]
Looks wrong. The first commit should not be in there.

**Comment by TomasHofman** [comment]
True, fixed.

**Comment by TomasHofman** [comment]
pom.xml was cleaned up

**Comment by wolfc** [comment]
:-1:

[ERROR] /home/carlo/work/jboss-set/mjolnir/src/main/java/org/jboss/mjolnir/client/component/administration/EditUserDialog.java:[73,46] error: unreported exception GitHubNameAlreadyTakenException; must be caught or declared to be thrown

**Comment by TomasHofman** [comment]
Compilation error is fixed. Don't know how that could happen...

**Pull request merged**
